name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python-lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.10, 3.11]
    steps:
      - uses: actions/checkout@v3

      # Cache pip
      - name: Cache Python wheels
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with: python-version: ${{ matrix.python }}

      - name: Install deps
        run: pip install ruff mypy pytest

      - name: Lint (ruff)
        run: ruff infra/ backend/ ml/

      - name: Type-check (mypy)
        run: mypy backend/ ml/

      - name: Run unit tests
        run: pytest backend/ ml/

  node-lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      # Cache node_modules
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: |
          cd frontend
          npm ci

      - name: Lint + Type-check (TS-ESLint)
        run: |
          cd frontend
          npx eslint . --ext .ts,.tsx

      - name: Run unit tests
        run: |
          cd frontend
          npm test

  docker-build:
    runs-on: ubuntu-latest
    needs: [python-lint-test, node-lint-test]
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t zaynahmed0/gliax-cloud:ci .

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        run: docker push ghcr.io/zaynahmed0/gliax-cloud:ci 